apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: speedtest
  namespace: default
  labels:
    k8s-app: speedtest
spec:
  selector:
    matchLabels:
      name: speedtest
  template:
    metadata:
      labels:
        name: speedtest
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: substrate
        image: pmjohann/nodetest:latest
        env:
          - name: MASTER_IP
            value: 172.104.230.140
          - name: TOTAL_NODES
            value: "31"
        ports:
          - containerPort: 30333
            hostPort: 30333
          - containerPort: 9944
      - name: redis
        image: redis:alpine
        ports:
          - containerPort: 6379
